### ISSUE TITLE
Generate .gitignore using gitignore.io

### ISSUE THREAD

**Issue by sambhav2612** [scorelab/D4D---Drone-4-Dengue#33]
Technologies Identified: `Java(Android)` and `Python`

[GCI Participation // Task: [Git] Create a shiny new .gitignore for any of the SCoRe projects]

**Comment by agentmilindu** [comment]
@Lasith-Niro @Akarshani Can you confirm is there two technologies are the ones we should use to generate a  `.gitignore` from gitignore.io?

**Comment by agentmilindu** [comment]
I think we have to ignore `intellij+iml` also.

**Comment by agentmilindu** [comment]
@sambhav2612 You are good to go, let's generate the .gitignore file

**Comment by sambhav2612** [comment]
it's done see #35
